project:
  type: website

website:
  title: "Statisitical Learning for Data Mining Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project1.qmd
        text: Bias and Variance in Linear Regression
      - href: project2.qmd
        text: Ensemble Learning Techniques for Fair Classification
      - href: project3.qmd
        text: Forecasting Property Valuations in a Mid-Sized U.S. City: A SHAP-Gain Feature Selection and ElasticNet-Ensembled Approach with Optuna-Tuned XGBoost

format:
  html:
    theme: cosmo
    toc: true
